In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np


In [ ]:
np.array([[1,2,3],[2,2,2]])

array([[1, 2, 3],
       [2, 2, 2]])

In [ ]:
np.zeros((5,5), dtype='int64')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.ones((5,5), dtype='int64')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
for i in range(10):
  print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
np.random.random(5)

array([0.63767958, 0.60552487, 0.87787184, 0.76173577, 0.74062767])

In [ ]:
np.random.randint(20, size=(2,3))

array([[14,  1, 12],
       [11, 14, 12]])

In [ ]:
a=np.ones((5,5))
b=np.ones((5,5))

a+b

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [ ]:
np.sin(a)

array([[0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098]])

In [ ]:
a=np.random.randint(40, size=(2,3))
a

array([[29, 14, 30],
       [21, 34, 25]])

In [ ]:
a.max(axis=0)

array([29, 34, 30])

In [ ]:
a.max(axis=1)

array([30, 34])

In [ ]:
a=np.array([[1,2],[2,5]])
b=np.array([[2],[8]])


In [ ]:
a.dot(b)

array([[18],
       [44]])

In [ ]:
np.matmul(a,b)

array([[18],
       [44]])

In [ ]:
a=np.array([[1,2],[2,5]])
b=np.array([[2],[8]])


In [ ]:
a+b

array([[ 3,  4],
       [10, 13]])

In [ ]:
np.linalg.inv(a)

array([[ 5., -2.],
       [-2.,  1.]])

In [ ]:
np.linalg.solve(a,b)

array([[-6.],
       [ 4.]])

#Problem 1


In [ ]:
#1.1
np.empty((2,2))


array([[ 5., -2.],
       [-2.,  1.]])

In [ ]:
#1.2
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
#1.3
np.full((3, 4), 7, dtype=int)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
#1.4
a = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=float)
np.zeros_like(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#1.5
a = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=float)
np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#1.6
new_list = [1, 2, 3, 4]

np.array(new_list)


array([1, 2, 3, 4])

#Problem 2

In [ ]:
#2.1
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [ ]:
#2.2
np.arange(9).reshape(3, 3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#2.3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#2.4
a=np.random.random(30)
a.mean()

np.float64(0.5082252731371998)

In [ ]:
#2.5
a=np.random.randint(40, size=(10,10))
a.max()

np.int64(39)

In [ ]:
a.min()

np.int64(0)

In [ ]:
#2.6
a = np.zeros(10)
a[4] = 1
a


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
#2.7
arr = np.array([1, 2, 0, 0, 4, 0])
np.flip(arr)

array([0, 4, 0, 0, 2, 1])

In [ ]:
#.28

arr = np.ones((6, 4), dtype=int)

arr[1:-1, 1:-1] = 0
arr

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

In [ ]:
#2.9

board = np.zeros((8, 8), dtype=int)
board[::2, ::2] = 1
board[1::2, 1::2] = 1

print(board)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#Problem 3

In [ ]:

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1
print("1. Addition:")
print("x + y =\n", x + y)
print()

# 2
print("2. Subtraction:")
print("x - y =\n", x - y)
print()

# 3
print("3. Multiplication with integers:")
print("x * 3 =\n", x * 3)
print("y * 2 =\n", y * 2)
print()

# 4.
print("4. Square of each element:")
print("x² =\n", x**2)
print("y² =\n", y**2)
print("v² =", v**2)
print()

# 5.
print("5. Dot products:")
print("v · w =", np.dot(v, w))
print("x · v =", np.dot(x, v))
print("x · y =\n", np.dot(x, y))
print()

# 6.
print("6. Concatenation:")
xyrow = np.concatenate((x, y), axis=0)
print("x and y along rows:\n", xyrow)

# Concatenate v and w along column
vwcol = np.column_stack((v, w))
print("v and w along columns:\n", vwcol)


1. Addition:
x + y =
 [[ 6  8]
 [10 13]]

2. Subtraction:
x - y =
 [[-4 -4]
 [-4 -3]]

3. Multiplication with integers:
x * 3 =
 [[ 3  6]
 [ 9 15]]
y * 2 =
 [[10 12]
 [14 16]]

4. Square of each element:
x² =
 [[ 1  4]
 [ 9 25]]
y² =
 [[25 36]
 [49 64]]
v² = [ 81 100]

5. Dot products:
v · w = 219
x · v = [29 77]
x · y =
 [[19 22]
 [50 58]]

6. Concatenation:
x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w along columns:
 [[ 9 11]
 [10 12]]


In [ ]:
#7
np.concatenate((x,v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

we get error because x is 2d array and v is 1 d array. the concatenacion requires both arrays to have the same number of dimensions.


#Problem 4


In [ ]:

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])


# 1.
A_inv = np.linalg.inv(A)
print("A inverse =\n", A_inv)

eye = np.dot(A, A_inv)
print("A.A⁻¹ =\n", eye)


A inverse =
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A.A⁻¹ =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
# 2. Prove AB not equals to BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA)

are_equal = np.array_equal(AB, BA)
print("Are AB and BA equal?", are_equal)




In [ ]:
# 3.
AB=np.dot(A,B)
ABtransp = AB.T
print("AB transpose", ABtransp)

Btransp = B.T
Atransp = A.T
BT_AT = np.dot(Btransp, Atransp)
print("B transpose . A Transpose =\n", BT_AT)

equal = np.array_equal(ABtransp, BT_AT)
print("Are (AB)Transpose and BTranspose.ATranspose equal?", equal)


AB transpose [[23 51]
 [13 29]]
B transpose . A Transpose =
 [[23 51]
 [13 29]]
Are (AB)Transpose and BTranspose.ATranspose equal? True
